# Generated by Django 5.2.7 on 2026-03-28 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('student_id', models.CharField(max_length=50)),
                ('technology', models.CharField(choices=[('Java', 'Java'), ('Python', 'Python'), ('Web Development', 'Web Development'), ('Data Science', 'Data Science'), ('UI/UX Design', 'UI/UX Design'), ('React.js', 'React.js')], max_length=50)),
                ('today_topic', models.CharField(max_length=200)),
                ('batch_time', models.TimeField()),
                ('trainer_name', models.CharField(choices=[('Amit Sharma', 'Amit Sharma'), ('Priya Singh', 'Priya Singh'), ('Rajesh Kumar', 'Rajesh Kumar'), ('Sneha Gupta', 'Sneha Gupta')], max_length=100)),
                ('student_batch', models.CharField(choices=[('Batch A', 'Batch A'), ('Batch B', 'Batch B'), ('Batch C', 'Batch C')], max_length=20)),
                ('week_type', models.CharField(choices=[('Weekdays', 'Weekdays'), ('Weekend', 'Weekend')], max_length=20)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
