# Generated by Django 5.2.7 on 2026-03-28 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='student_batch',
            field=models.CharField(blank=True, choices=[('Batch A', 'Batch A'), ('Batch B', 'Batch B'), ('Batch C', 'Batch C'), ('Weekdays', 'Weekdays'), ('Weekend', 'Weekend')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='technology',
            field=models.CharField(choices=[('Java', 'Java'), ('Python', 'Python'), ('Web Development', 'Web Development'), ('Data Science', 'Data Science'), ('UI/UX Design', 'UI/UX Design'), ('React.js', 'React.js'), ('MERN', 'MERN'), ('Graphic Design', 'Graphic Design'), ('Cloud', 'Cloud'), ('Ethical Hacking', 'Ethical Hacking'), ('Cyber Security', 'Cyber Security'), ('Digital Marketing', 'Digital Marketing'), ('AutoCAD', 'AutoCAD'), ('Flutter', 'Flutter'), ('Web Design', 'Web Design'), ('PD', 'PD')], max_length=50),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='trainer_name',
            field=models.CharField(choices=[('MR. AMAN (DATA SCIENCE)', 'MR. AMAN (DATA SCIENCE)'), ('MR. ABDUL (DATA ANALYTICS)', 'MR. ABDUL (DATA ANALYTICS)'), ('MR. PRASHANT (GRAPHIC)', 'MR. PRASHANT (GRAPHIC)'), ('MR. SAGAR (CLOUD)', 'MR. SAGAR (CLOUD)'), ('MR. RAJESH (JAVA)', 'MR. RAJESH (JAVA)'), ('MR. HEMANT (ETHICAL)', 'MR. HEMANT (ETHICAL)'), ('MRS. MAMTA (MERN)', 'MRS. MAMTA (MERN)'), ('MR. SOUVIK (CYBER)', 'MR. SOUVIK (CYBER)'), ('MRS NITI GUPTA (PD)', 'MRS NITI GUPTA (PD)'), ('AMAN KHAN (DIGITAL MARKETING)', 'AMAN KHAN (DIGITAL MARKETING)'), ('MR. RUPINDER (AUTOCAD)', 'MR. RUPINDER (AUTOCAD)'), ('MR. AMAN SIR (FLUTTER)', 'MR. AMAN SIR (FLUTTER)'), ('MR. PRATEEK (WEB-DESIGN)', 'MR. PRATEEK (WEB-DESIGN)'), ('MR. TARUN (MERN)', 'MR. TARUN (MERN)')], max_length=100),
        ),
    ]
