# Generated by Django 6.0.3 on 2026-03-29 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0002_alter_attendance_student_batch_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='batch_mode',
            field=models.CharField(choices=[('Online', 'Online'), ('Offline', 'Offline')], default='Offline', max_length=10),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='technology',
            field=models.CharField(choices=[('DATA ANALYTICS & AI', 'DATA ANALYTICS & AI'), ('DATA ANALYTICS & GEN AI', 'DATA ANALYTICS & GEN AI'), ('PYTHON FULLSTACK', 'PYTHON FULLSTACK'), ('JAVA FULLSTACK', 'JAVA FULLSTACK'), ('DATA SCIENCE', 'DATA SCIENCE'), ('FLUTTER', 'FLUTTER'), ('SAP', 'SAP'), ('DEVOPS MASTER', 'DEVOPS MASTER'), ('DIPLOMA CLOUD COMPUTING', 'DIPLOMA CLOUD COMPUTING'), ('DIPLOMA CYBER ETHICAL', 'DIPLOMA CYBER ETHICAL'), ('DIPLOMA DIGITAL MARKETING', 'DIPLOMA DIGITAL MARKETING'), ('DIGITAL MARKETING', 'DIGITAL MARKETING'), ('GRAPHIC/MOTION', 'GRAPHIC/MOTION'), ('PD CLASS', 'PD CLASS'), ('MERN/MEAN STACK', 'MERN/MEAN STACK'), ('MIS', 'MIS'), ('AUTOCAD/SOLIDWORKS', 'AUTOCAD/SOLIDWORKS'), ('BUSINESS ANALYTICS', 'BUSINESS ANALYTICS'), ('UI/UX', 'UI/UX'), ('WEBDESIGN', 'WEBDESIGN'), ('JAVA EXPERT', 'JAVA EXPERT'), ('ANDROID/KOTLIN', 'ANDROID/KOTLIN'), ('GEN AI', 'GEN AI'), ('CCNA', 'CCNA'), ('SQT & CORE JAVA', 'SQT & CORE JAVA')], max_length=50),
        ),
    ]
