# Generated by Django 5.2.7 on 2026-03-29 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0003_attendance_batch_mode_alter_attendance_technology'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='student_batch',
        ),
    ]
