# Generated by Django 5.2.7 on 2026-03-29 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0004_remove_attendance_student_batch'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('sid', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('course', models.CharField(max_length=100)),
                ('semester', models.CharField(max_length=20)),
                ('section', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='attendance',
            name='section',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='semester',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
