# Generated by Django 5.2.7 on 2026-03-30 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0005_student_attendance_section_attendance_semester'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='technology',
            field=models.CharField(choices=[('DATA ANALYTICS & AI', 'DATA ANALYTICS & AI'), ('DATA ANALYTICS & GEN AI', 'DATA ANALYTICS & GEN AI'), ('PYTHON FULLSTACK', 'PYTHON FULLSTACK'), ('JAVA FULLSTACK', 'JAVA FULLSTACK'), ('DATA SCIENCE', 'DATA SCIENCE'), ('FLUTTER', 'FLUTTER'), ('SAP', 'SAP'), ('DEVOPS MASTER', 'DEVOPS MASTER'), ('DIPLOMA CLOUD COMPUTING', 'DIPLOMA CLOUD COMPUTING'), ('DIPLOMA CYBER ETHICAL', 'DIPLOMA CYBER ETHICAL'), ('DIPLOMA DIGITAL MARKETING', 'DIPLOMA DIGITAL MARKETING'), ('DIGITAL MARKETING', 'DIGITAL MARKETING'), ('GRAPHIC/MOTION', 'GRAPHIC/MOTION'), ('DIPLOMA GRAPHIC DESIGN', 'DIPLOMA GRAPHIC DESIGN'), ('C & C++', 'C & C++'), ('SELENIUM JAVA', 'SELENIUM JAVA'), ('PYTHON WITH AI', 'PYTHON WITH AI'), ('REVIT', 'REVIT'), ('PD CLASS', 'PD CLASS'), ('MERN/MEAN STACK', 'MERN/MEAN STACK'), ('MIS', 'MIS'), ('AUTOCAD/SOLIDWORKS/3DS MAX', 'AUTOCAD/SOLIDWORKS/3DS MAX'), ('BUSINESS ANALYTICS', 'BUSINESS ANALYTICS'), ('UI/UX', 'UI/UX'), ('WEBDESIGN', 'WEBDESIGN'), ('JAVA EXPERT', 'JAVA EXPERT'), ('ANDROID/KOTLIN', 'ANDROID/KOTLIN'), ('GEN AI', 'GEN AI'), ('CCNA', 'CCNA'), ('SQT & CORE JAVA', 'SQT & CORE JAVA')], max_length=50),
        ),
    ]
