# Generated by Django 5.2.7 on 2026-04-01 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0007_alter_student_section_alter_student_semester'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='batch_time',
            field=models.CharField(max_length=20),
        ),
    ]
