# Generated by Django 6.0.3 on 2026-04-01 18:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0009_student_current_batch_student_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='joining_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
