# Generated by Django 5.2.7 on 2026-03-29 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=50)),
                ('student_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('branch', models.CharField(default='Vikaspuri', max_length=100)),
                ('trainer_name', models.CharField(max_length=255)),
                ('technology', models.CharField(max_length=255)),
                ('batch_timing', models.CharField(max_length=100)),
                ('ques1_rating', models.IntegerField(default=5)),
                ('ques2_rating', models.IntegerField(default=5)),
                ('ques3_rating', models.IntegerField(default=5)),
                ('ques4_rating', models.IntegerField(default=5)),
                ('review_description', models.TextField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
