# Generated by Django 5.2.7 on 2026-03-29 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='batch_mode',
            field=models.CharField(default='Offline', max_length=20),
        ),
    ]
