# Generated by Django 5.2.7 on 2026-03-29 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_feedback_batch_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='batch_type',
            field=models.CharField(default='Weekdays', max_length=20),
        ),
        migrations.AddField(
            model_name='feedback',
            name='phase',
            field=models.CharField(default='P-1', max_length=10),
        ),
    ]
