# Generated by Django 5.2.7 on 2026-03-31 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0003_feedback_batch_type_feedback_phase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='phase',
            field=models.CharField(choices=[('P-1', 'Phase 1: Orientation & Basics'), ('P-2', 'Phase 2: Core Implementation'), ('P-3', 'Phase 3: Mid-Project Assessment'), ('P-4', 'Phase 4: Advanced Concepts'), ('P-5', 'Phase 5: Final Submission/Project')], default='P-1', max_length=10),
        ),
    ]
