# Generated by Django 5.2.3 on 2026-04-04 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feedback", "0007_alter_feedback_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feedback",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
