# Generated by Django 5.2.7 on 2026-03-28 07:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('course', models.CharField(max_length=100)),
                ('current_topic', models.CharField(default='Orientation', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_type', models.CharField(choices=[('Weekday', 'Weekday'), ('Weekend', 'Weekend')], max_length=20)),
                ('students_count', models.IntegerField(default=0)),
                ('timing', models.CharField(max_length=100)),
                ('month', models.CharField(max_length=20)),
                ('year', models.CharField(max_length=4)),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='dashboard.trainer')),
            ],
        ),
    ]
