# Generated by Django 5.2.7 on 2026-03-29 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='batch_type',
            field=models.CharField(choices=[('Weekdays', 'Weekdays'), ('Weekend', 'Weekend')], max_length=20),
        ),
    ]
