# Generated by Django 6.0.3 on 2026-04-01 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_batch_batch_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='batch_name',
            field=models.CharField(choices=[('PYTHON', 'PYTHON'), ('POWER BI', 'POWER BI'), ('EXCEL', 'EXCEL'), ('SQL', 'SQL'), ('TABLEAU', 'TABLEAU'), ('MACHINE LEARNING', 'MACHINE LEARNING'), ('NLP', 'NLP'), ('GEN AI', 'GEN AI'), ('CORE JAVA', 'CORE JAVA'), ('ADVANCED JAVA', 'ADVANCED JAVA'), ('REACT JS', 'REACT JS'), ('NODE JS', 'NODE JS'), ('MONGODB', 'MONGODB'), ('OTHERS', 'OTHERS')], default='OTHERS', max_length=100),
        ),
        migrations.AlterField(
            model_name='batch',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
