# Generated by Django 6.0.3 on 2026-04-01 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_batch_batch_name_alter_batch_id_alter_trainer_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainer',
            name='current_topic',
        ),
    ]
