# Generated by Django 6.0.3 on 2026-04-01 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_remove_trainer_current_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='batch',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
